fix: update dry-run and publish conflict logic for npm>=10 (#232)

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -25,9 +25,11 @@ jobs:
           - macos-latest
           - windows-latest
         node-version:
-          - 16
-          - 18
-          - 20
+          - "16"
+          - "18"
+          - "20"
+          - "22"
+          - "24"
 
     steps:
       - name: Checkout source
@@ -107,9 +109,11 @@ jobs:
       fail-fast: false
       matrix:
         node-version:
-          - 16
-          - 18
-          - 20
+          - "16"
+          - "18"
+          - "20"
+          - "22"
+          - "24"
 
     services:
       verdaccio:
@@ -173,6 +177,21 @@ jobs:
         shell: bash
         run: ./e2e/01-setup-package.sh "${{ steps.setup.outputs.package }}" 0.0.3
 
+      - id: action-publish-dry-before
+        name: Publish a dry run before publish
+        uses: ./
+        with:
+          registry: http://localhost:4873
+          package: ${{ steps.setup.outputs.package }}/package.json
+          token: ${{ steps.setup.outputs.token }}
+          dry-run: true
+
+      - name: Check release output
+        if: ${{ steps.action-publish-dry-before.outputs.type != 'patch' }}
+        run: |
+          echo "::error::Expected release type to be 'patch', got '${{ steps.action-publish-dry-before.outputs.type }}'"
+          exit 1
+
       - id: action-publish
         name: Publish a new version
         uses: ./
@@ -187,8 +206,8 @@ jobs:
           echo "::error::Expected release type to be 'patch', got '${{ steps.action-publish.outputs.type }}'"
           exit 1
 
-      - id: action-publish-dry
-        name: Publish a dry run
+      - id: action-publish-dry-after
+        name: Publish a dry run after publish
         uses: ./
         with:
           registry: http://localhost:4873
@@ -197,9 +216,9 @@ jobs:
           dry-run: true
 
       - name: Check release output
-        if: ${{ steps.action-publish-dry.outputs.type }}
+        if: ${{ steps.action-publish-dry-after.outputs.type }}
         run: |
-          echo "::error::Expected release type to be '', got '${{ steps.action-publish-dry.outputs.type }}'"
+          echo "::error::Expected release type to be '', got '${{ steps.action-publish-dry-after.outputs.type }}'"
           exit 1
 
   deploy:
